
FROM node:23-slim

WORKDIR /home/node/app

RUN npm install -g npm@latest

COPY package*.json ./

# wait-for-it
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

RUN npm install

CMD ["npm", "run", "dev"]
